openapi: 3.0.0
components:
  schemas:
    MenuItem:
      type: object
      description: Complete menu item with stock tracking fields
      properties:
        id:
          type: integer
          format: int32
          description: Unique identifier for the menu item
          example: 1
        categoryId:
          type: integer
          format: int32
          description: ID of the category this item belongs to
          example: 1
        name:
          type: string
          description: Item's name
          example: "Bandeja Paisa"
        description:
          type: string
          nullable: true
          description: Item's description
          example: "Traditional Colombian platter with beans, rice, meat, and more"
        price:
          type: number
          format: decimal
          description: Price of the item in local currency
          example: 25000.00
        isExtra:
          type: boolean
          description: Whether the item is an extra/add-on
          example: false
        isAvailable:
          type: boolean
          description: Whether the item is currently available for ordering
          example: true
        imageUrl:
          type: string
          format: uri
          nullable: true
          description: URL of the item's image
          example: "https://cloudinary.com/plaet/items/bandeja-paisa.jpg"
        inventoryType:
          type: string
          enum:
            - TRACKED
            - UNLIMITED
          description: |
            Inventory tracking mode:
            - TRACKED: Limited daily stock with tracking
            - UNLIMITED: Always available (no tracking)
          example: "TRACKED"
        stockQuantity:
          type: integer
          format: int32
          nullable: true
          description: Current stock quantity (null for UNLIMITED items)
          example: 18
        initialStock:
          type: integer
          format: int32
          nullable: true
          description: Initial stock quantity set at day start
          example: 30
        lowStockAlert:
          type: integer
          format: int32
          nullable: true
          description: Stock threshold for low stock alerts
          example: 5
        autoMarkUnavailable:
          type: boolean
          description: Whether to auto-block item when stock reaches zero
          example: true
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          example: "2025-01-15T10:00:00.000Z"
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2025-11-17T14:30:00.000Z"
        deleted:
          type: boolean
          description: Soft delete status
          example: false
        deletedAt:
          type: string
          format: date-time
          nullable: true
          description: Deletion timestamp, if deleted
          example: null

    CreateItemRequest:
      type: object
      description: |
        Request body for creating a new menu item.
        Inventory fields are optional and default to UNLIMITED type.
      required:
        - name
        - description
        - categoryId
        - price
        - isExtra
        - isAvailable
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 100
          description: Item's name (must be unique within category)
          example: "Bandeja Paisa"
        description:
          type: string
          minLength: 10
          maxLength: 500
          description: Item's description
          example: "Traditional Colombian platter with beans, rice, meat, fried egg, plantain, arepa, and avocado"
        categoryId:
          type: integer
          format: int32
          minimum: 1
          description: ID of the category this item belongs to
          example: 1
        price:
          type: number
          format: decimal
          minimum: 0
          description: Price of the item in local currency
          example: 25000.00
        isExtra:
          type: boolean
          description: Whether the item is an extra/add-on
          example: false
        isAvailable:
          type: boolean
          description: Whether the item is available for ordering
          example: true
        imageUrl:
          type: string
          format: uri
          description: URL of the item's image (optional)
          example: "https://cloudinary.com/plaet/items/bandeja-paisa.jpg"
        inventoryType:
          type: string
          enum:
            - TRACKED
            - UNLIMITED
          description: |
            Inventory tracking mode (optional, defaults to UNLIMITED):
            - TRACKED: Limited daily stock requiring tracking
            - UNLIMITED: Always available with no stock limits
          example: "UNLIMITED"
        lowStockAlert:
          type: integer
          format: int32
          minimum: 0
          description: Stock threshold for alerts (only for TRACKED items)
          example: 5
        autoMarkUnavailable:
          type: boolean
          description: Auto-block item when stock reaches zero (only for TRACKED)
          example: true

    MenuItemResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the request was successful
          example: true
        message:
          type: string
          description: Response message
          example: "Item created successfully"
        data:
          $ref: "#/components/schemas/MenuItem"

    MenuItemListResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the operation was successful
          example: true
        message:
          type: string
          description: Descriptive message about operation
          example: "Menu Items fetched successfully"
        data:
          type: array
          items:
            $ref: "#/components/schemas/MenuItem"
          description: Array of Menu Items objects
        meta:
          type: object
          properties:
            page:
              type: integer
              description: Current page number
              example: 1
            limit:
              type: integer
              description: Number of items per page
              example: 10
            total:
              type: integer
              description: Total number of Menu Items
              example: 25
            totalPages:
              type: integer
              description: Total number of pages
              example: 3
          description: Pagination metadata

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the request was successful
          example: false
        message:
          type: string
          description: Error message
          example: "Invalid request parameters"
        error:
          type: string
          description: Error type
          example: "BAD_REQUEST"
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                description: Field that caused the error
                example: "name"
              message:
                type: string
                description: Error message for the field
                example: "Name must be at least 3 characters long"
