openapi: 3.0.0
components:
  schemas:
    # ============================================
    # SCHEMA: DailyStockResetRequest
    # ============================================
    DailyStockResetRequest:
      type: object
      description: |
        Request body for daily stock reset operation.
        Used to initialize stock quantities at the start of each business day.
      required:
        - items
      properties:
        items:
          type: array
          description: Array of menu items to initialize with stock quantities
          minItems: 1
          items:
            type: object
            required:
              - itemId
              - quantity
            properties:
              itemId:
                type: integer
                format: int32
                minimum: 1
                description: Menu item identifier (must be TRACKED inventory type)
                example: 1
              quantity:
                type: integer
                format: int32
                minimum: 0
                description: Initial stock quantity for the day (number of portions)
                example: 30
              lowStockAlert:
                type: integer
                format: int32
                minimum: 0
                description: Stock threshold that triggers low stock alerts
                example: 5

    # ============================================
    # SCHEMA: AddStockRequest
    # ============================================
    AddStockRequest:
      type: object
      description: |
        Request body for adding stock manually to a menu item.
        Used for mid-day production additions or inventory corrections.
      required:
        - quantity
        - reason
      properties:
        quantity:
          type: integer
          format: int32
          minimum: 1
          description: Number of units to add to current stock
          example: 15
        reason:
          type: string
          minLength: 3
          maxLength: 200
          description: Explanation for the stock addition (required for audit trail)
          example: "Additional mid-day production due to high demand"

    # ============================================
    # SCHEMA: RemoveStockRequest
    # ============================================
    RemoveStockRequest:
      type: object
      description: |
        Request body for removing stock manually from a menu item.
        Used for waste, spoilage, damage, or other stock reductions.
      required:
        - quantity
      properties:
        quantity:
          type: integer
          format: int32
          minimum: 1
          description: Number of units to remove from current stock
          example: 3
        reason:
          type: string
          minLength: 3
          maxLength: 200
          description: Explanation for the stock removal (optional but recommended)
          example: "Dishes dropped during service - kitchen accident"

    # ============================================
    # SCHEMA: InventoryTypeRequest
    # ============================================
    InventoryTypeRequest:
      type: object
      description: |
        Request body for configuring inventory tracking type.
        Determines whether item requires stock tracking or has unlimited availability.
      required:
        - inventoryType
      properties:
        inventoryType:
          type: string
          enum:
            - TRACKED
            - UNLIMITED
          description: |
            Inventory tracking mode:
            - TRACKED: Limited daily stock with tracking
            - UNLIMITED: Always available (no tracking)
          example: "TRACKED"
        lowStockAlert:
          type: integer
          format: int32
          minimum: 0
          description: Stock threshold for low stock alerts (only for TRACKED items)
          example: 5

    # ============================================
    # SCHEMA: MenuItem (Extended with Stock Fields)
    # ============================================
    MenuItemWithStock:
      type: object
      description: Complete menu item with stock tracking fields
      properties:
        id:
          type: integer
          format: int32
          description: Unique menu item identifier
          example: 1
        categoryId:
          type: integer
          format: int32
          description: Associated menu category identifier
          example: 2
        name:
          type: string
          description: Menu item name
          example: "Bandeja Paisa"
        description:
          type: string
          nullable: true
          description: Menu item description
          example: "Traditional Colombian platter with beans, rice, meat, and more"
        price:
          type: number
          format: decimal
          description: Item price in local currency
          example: 25000.00
        isExtra:
          type: boolean
          description: Whether item is an extra/add-on
          example: false
        isAvailable:
          type: boolean
          description: Whether item is currently available for ordering
          example: true
        imageUrl:
          type: string
          format: uri
          nullable: true
          description: URL of item image
          example: "https://cloudinary.com/plaet/items/bandeja-paisa.jpg"
        inventoryType:
          type: string
          enum:
            - TRACKED
            - UNLIMITED
          description: Inventory tracking mode
          example: "TRACKED"
        stockQuantity:
          type: integer
          format: int32
          nullable: true
          description: Current stock quantity (null for UNLIMITED items)
          example: 18
        initialStock:
          type: integer
          format: int32
          nullable: true
          description: Initial stock quantity set at day start
          example: 30
        lowStockAlert:
          type: integer
          format: int32
          nullable: true
          description: Stock threshold for low stock alerts
          example: 5
        autoMarkUnavailable:
          type: boolean
          description: Whether to auto-block item when stock reaches zero
          example: true
        createdAt:
          type: string
          format: date-time
          description: Item creation timestamp
          example: "2025-01-15T10:00:00.000Z"
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2025-10-14T14:30:00.000Z"
        deleted:
          type: boolean
          description: Soft delete status
          example: false
        deletedAt:
          type: string
          format: date-time
          nullable: true
          description: Deletion timestamp (if deleted)
          example: null

    # ============================================
    # SCHEMA: StockAdjustment
    # ============================================
    StockAdjustment:
      type: object
      description: Stock adjustment audit record
      properties:
        id:
          type: string
          format: uuid
          description: Unique adjustment identifier
          example: "123e4567-e89b-12d3-a456-426614174000"
        menuItemId:
          type: integer
          format: int32
          description: Menu item identifier
          example: 1
        adjustmentType:
          type: string
          enum:
            - DAILY_RESET
            - MANUAL_ADD
            - MANUAL_REMOVE
            - ORDER_DEDUCT
            - ORDER_CANCELLED
          description: Type of stock adjustment
          example: "MANUAL_ADD"
        previousStock:
          type: integer
          format: int32
          description: Stock quantity before adjustment
          example: 18
        newStock:
          type: integer
          format: int32
          description: Stock quantity after adjustment
          example: 33
        quantity:
          type: integer
          format: int32
          description: Amount changed (positive for add, negative for remove)
          example: 15
        reason:
          type: string
          nullable: true
          description: Explanation for the adjustment
          example: "Additional mid-day production"
        userId:
          type: string
          format: uuid
          nullable: true
          description: User who performed the adjustment
          example: "550e8400-e29b-41d4-a716-446655440001"
        orderId:
          type: string
          format: uuid
          nullable: true
          description: Order associated with adjustment (for ORDER_DEDUCT/ORDER_CANCELLED)
          example: null
        createdAt:
          type: string
          format: date-time
          description: Adjustment timestamp
          example: "2025-10-14T14:30:00.000Z"

    # ============================================
    # SCHEMA: StockHistoryResponse
    # ============================================
    StockHistoryResponse:
      type: object
      description: Paginated stock adjustment history response
      properties:
        success:
          type: boolean
          description: Operation success status
          example: true
        message:
          type: string
          description: Response message
          example: "Stock History fetched successfully"
        data:
          type: object
          properties:
            data:
              type: array
              description: Array of stock adjustment records
              items:
                $ref: "#/components/schemas/StockAdjustment"
            meta:
              type: object
              description: Pagination metadata
              properties:
                total:
                  type: integer
                  description: Total number of adjustments
                  example: 45
                page:
                  type: integer
                  description: Current page number
                  example: 1
                limit:
                  type: integer
                  description: Records per page
                  example: 20
                totalPages:
                  type: integer
                  description: Total number of pages
                  example: 3

    # ============================================
    # SCHEMA: MenuItemResponse
    # ============================================
    MenuItemResponse:
      type: object
      description: Successful menu item operation response
      properties:
        success:
          type: boolean
          description: Operation success status
          example: true
        message:
          type: string
          description: Response message
          example: "Stock added successfully"
        data:
          $ref: "#/components/schemas/MenuItemWithStock"

    # ============================================
    # SCHEMA: MenuItemListResponse
    # ============================================
    MenuItemListResponse:
      type: object
      description: List of menu items response
      properties:
        success:
          type: boolean
          description: Operation success status
          example: true
        message:
          type: string
          description: Response message
          example: "Low stock items fetched successfully"
        data:
          type: array
          items:
            $ref: "#/components/schemas/MenuItemWithStock"

    # ============================================
    # SCHEMA: SuccessResponse (No Data)
    # ============================================
    SuccessResponseNoData:
      type: object
      description: Successful operation response without data
      properties:
        success:
          type: boolean
          description: Operation success status
          example: true
        message:
          type: string
          description: Response message
          example: "Daily stock reset successfully"

    # ============================================
    # SCHEMA: ErrorResponse
    # ============================================
    ErrorResponse:
      type: object
      description: Standard error response
      properties:
        success:
          type: boolean
          description: Always false for errors
          example: false
        status:
          type: integer
          description: HTTP status code
          example: 400
        message:
          type: string
          description: Error message description
          example: "Validation failed"
        code:
          type: string
          description: Internal error code
          example: "VALIDATION_ERROR"
        errors:
          type: array
          description: Detailed validation errors (optional)
          items:
            type: object
            properties:
              field:
                type: string
                description: Field that caused the error
                example: "quantity"
              message:
                type: string
                description: Field-specific error message
                example: "Quantity must be positive"
