openapi: 3.0.0
paths:
  /menu/categories/search:
    get:
      tags:
        - Menu Categories
      summary: Search menu categories with filtering and pagination
      description: |
        Search for menu categories by name and filter by active status.
        Supports pagination and case-insensitive name search.
      parameters:
        - in: query
          name: search
          schema:
            type: string
            minLength: 1
            maxLength: 100
          description: Search term for filtering categories by name (case-insensitive)
          example: "main"
        - in: query
          name: active
          schema:
            type: string
            enum: ["true", "false"]
          description: Filter categories by active status
          example: "true"
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
          example: 1
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
          description: Number of items per page
          example: 20
      responses:
        200:
          description: Menu categories search completed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MenuCategoryListResponse"
              example:
                success: true
                message: "Menu Categories search completed successfully"
                data:
                  items:
                    - id: 1
                      name: "Main Dishes"
                      description: "Primary meal options"
                      order: 1
                      deleted: false
                      deletedAt: null
                    - id: 3
                      name: "Main Course"
                      description: "Main course selections"
                      order: 3
                      deleted: false
                      deletedAt: null
                  total: 2
                  page: 1
                  limit: 20
                  totalPages: 1
        400:
          description: Bad Request - Invalid search parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                status: 400
                message: "Invalid search parameters"
                errors:
                  - field: "search"
                    message: "Search term must be at least 1 character"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
