openapi: 3.0.0
components:
  schemas:
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
          example: admin@plaet.com
        password:
          type: string
          format: password
          description: User's password
          example: "admin123"

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: JWT access token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        user:
          $ref: "#/components/schemas/UserProfile"

    RegisterRequest:
      type: object
      required:
        - email
        - password
        - firstName
        - lastName
        - roleIds
      properties:
        email:
          type: string
          format: email
          description: User's email address
          example: newuser@example.com
        password:
          type: string
          format: password
          description: User's password
          example: "StrongP@ssw0rd"
        firstName:
          type: string
          description: User's first name
          example: "John"
        lastName:
          type: string
          description: User's last name
          example: "Doe"
        roleIds:
          type: array
          description: User's role ids
          items:
            type: integer
            minimum: 1
          example: [1, 3]

    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: User's unique identifiers
          example: "123e4567-e89b-12d3-a456-426614174000"
        email:
          type: string
          format: email
          description: User's email address
          example: "newuser@example.com"
        firstName:
          type: string
          description: User's first name
          example: "John"
        lastName:
          type: string
          description: User's last name
          example: "Doe"
        createdAt:
          type: string
          format: date-time
          description: User's registration date
          example: "2024-03-20T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Last update date
          example: "2024-03-20T10:00:00Z"

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code
          example: 400
        message:
          type: string
          description: Error message
          example: "Invalid request parameters"
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                description: Field that caused the error
                example: "email"
              message:
                type: string
                description: Error message for the field
                example: "Invalid email format"
