openapi: 3.0.0
paths:
  /menu/items:
    get:
      tags:
        - Menu Items
      summary: Get Menu Items
      description: Retrieve a paginated list of all menu items from the system. Supports pagination parameters for efficient data retrieval and display.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
          example: 1
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
          description: Number of items per page
          example: 10
      responses:
        200:
          description: Menu Items retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MenuItemListResponse"
              examples:
                menuItemList:
                  summary: Successful response with paginated menu items
                  value:
                    success: true
                    message: "Menu Items fetched successfully"
                    data:
                      - id: 1
                        categoryId: 1
                        name: "Spaghetti"
                        description: "Classic pasta with meat sauce"
                        price: 12000
                        isExtra: false
                        isAvailable: true
                        imageUrl: "https://example.com/images/spaghetti.jpg"
                        createdAt: "2024-01-15T10:30:00Z"
                        updatedAt: "2024-01-15T10:30:00Z"
                      - id: 2
                        categoryId: 1
                        name: "Pizza Margherita"
                        description: "Traditional Italian pizza"
                        price: 15000
                        isExtra: false
                        isAvailable: true
                        imageUrl: "https://example.com/images/pizza.jpg"
                        createdAt: "2024-02-15T10:30:00Z"
                        updatedAt: "2024-02-15T10:30:00Z"
                    meta:
                      page: 1
                      limit: 10
                      total: 25
                      totalPages: 3
        400:
          description: Bad Request - Invalid pagination parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                status: 400
                message: "Invalid pagination parameters"
                errors:
                  - field: "limit"
                    message: "Limit must be between 1 and 100"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /menus/items/{id}:
    get:
      tags:
        - Menu Items
      summary: Get a menu items by ID
      description: |
        Retrieves a specific menu item by its unique identifier 
        Returns the item regardless of its deleted status.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: Menu Item ID
          example: 3
      responses:
        200:
          description: Menu Item fetched successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MenuItemResponse"
              example:
                success: true
                message: "Menu Item fetched successfully"
                data:
                  id: 123
                  name: "Soda"
                  description: "Option for drink. Not include in main dish"
                  price: 5000
                  isExtra: false
                  isAvailable: true
                  imageUrl: "htts://imageurl.url"
        400:
          description: Bad Request - Invalid ID format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                status: 400
                message: "Invalid menu item ID format"
                errors:
                  - field: "id"
                    message: "ID must be a positive integer"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: Menu Item not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                status: 404
                message: "Menu Item ID 999 not found"
                errors:
                  - field: "id"
                    message: "Menu Item not found"
