openapi: 3.0.0
paths:
  /profiles:
    post:
      tags:
        - Profiles
      summary: Complete a user profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProfileRequest"
      responses:
        201:
          description: Profile updates succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileResponse"
        400:
          description: Bad Resquest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schema/ErrorResponse"
